# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a37a66c03626ed6e80923e9e3aadcf9115caf6f83929edfe43e12210943dfcc578ca42381bc32a7c8b62fcb8ab675a643a044e45936be5816902acc30b292bfb

test:
  secret_key_base: 098244575246a8cc98f6263d7c6ee73ca36732eb3e7e3b8f0f400016d9339050fd322f8062c014a45b7bdbd8ccf49f9f2db09bf59230757603cedf57a139ffe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
